/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boletin.pkg26;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author sbenavidesvazquez
 */
public class Bonoloto extends javax.swing.JFrame {

    /**
     * Creates new form Bonoloto
     */
    public Bonoloto() {
        initComponents();
    }

    int contador = 0;
    int vE1 = 0, vE2 = 0, vE3 = 0, vE4 = 0, vE5 = 0, vE6 = 0;
    int v1, v2, v3, v4, v5, v6;
    boolean check = false;

    Metodos obx = new Metodos();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botEmp = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tV1 = new javax.swing.JTextField();
        tV2 = new javax.swing.JTextField();
        tV3 = new javax.swing.JTextField();
        tV4 = new javax.swing.JTextField();
        tV5 = new javax.swing.JTextField();
        tV6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        num3 = new javax.swing.JTextField();
        num4 = new javax.swing.JTextField();
        num5 = new javax.swing.JTextField();
        num6 = new javax.swing.JTextField();
        Borrar = new javax.swing.JButton();
        bGV = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LA BONOLOTO");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("La Bonoloto.");

        botEmp.setText("Concursar");
        botEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEmpActionPerformed(evt);
            }
        });

        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(21, 14, 14), null));

        tV1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tV1ActionPerformed(evt);
            }
        });

        tV2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tV2ActionPerformed(evt);
            }
        });

        tV3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tV3ActionPerformed(evt);
            }
        });

        tV4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tV4ActionPerformed(evt);
            }
        });

        tV5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tV5ActionPerformed(evt);
            }
        });

        tV6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tV6ActionPerformed(evt);
            }
        });

        jLabel2.setText("ESCOGE UN NÚMERO ENTRE 1 Y 49 INCLUIDOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tV1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tV2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(tV3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(tV4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(tV5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tV6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tV6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        num1.setBorder(javax.swing.BorderFactory.createTitledBorder("num1"));
        num1.setMinimumSize(new java.awt.Dimension(12, 42));

        num2.setBorder(javax.swing.BorderFactory.createTitledBorder("num2"));

        num3.setBorder(javax.swing.BorderFactory.createTitledBorder("num3"));

        num4.setBorder(javax.swing.BorderFactory.createTitledBorder("num4"));

        num5.setBorder(javax.swing.BorderFactory.createTitledBorder("num5"));

        num6.setBorder(javax.swing.BorderFactory.createTitledBorder("num6"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        Borrar.setText("Reset");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        bGV.setText("Guardar valor");
        bGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(botEmp)
                .addGap(94, 94, 94)
                .addComponent(Borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bGV)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botEmp)
                    .addComponent(Borrar)
                    .addComponent(bGV))
                .addGap(65, 65, 65))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEmpActionPerformed
        if (botEmp == evt.getSource()) {

            if (check = true) {
                num1.setBackground(null);
                num2.setBackground(null);
                num3.setBackground(null);
                num4.setBackground(null);
                num5.setBackground(null);
                num6.setBackground(null);

                v1 = obx.aleatorio();
                num1.setText(Integer.toString(v1));

                v2 = obx.aleatorio();
                if (v2 == v1) {
                    v2 = obx.aleatorio();
                }
                num2.setText(Integer.toString(v2));

                v3 = obx.aleatorio();
                if (v3 == v1 || v3 == v2) {
                    v3 = obx.aleatorio();
                }
                num3.setText(Integer.toString(v3));

                v4 = obx.aleatorio();
                if (v4 == v1 || v4 == v3 || v4 == v2) {
                    v4 = obx.aleatorio();
                }
                num4.setText(Integer.toString(v4));

                v5 = obx.aleatorio();
                if (v5 == v1 || v5 == v3 || v5 == v4 || v5 == v2) {
                    v5 = obx.aleatorio();
                }
                num5.setText(Integer.toString(v5));

                v6 = obx.aleatorio();
                if (v6 == v1 || v6 == v3 || v6 == v4 || v6 == v5 || v6 == v2) {
                    v6 = obx.aleatorio();
                }
                num6.setText(Integer.toString(v6));

                if (v1 == vE1 || v1 == vE2 || v1 == vE3 || v1 == vE4 || v1 == vE5 || v1 == vE6) {
                    num1.setBackground(Color.green);
                }
                if (v2 == vE1 || v2 == vE2 || v2 == vE3 || v2 == vE4 || v2 == vE5 || v2 == vE6) {
                    num2.setBackground(Color.green);
                }
                if (v3 == vE1 || v3 == vE2 || v3 == vE3 || v3 == vE4 || v3 == vE5 || v3 == vE6) {
                    num3.setBackground(Color.green);
                }
                if (v4 == vE1 || v4 == vE2 || v4 == vE3 || v4 == vE4 || v4 == vE5 || v4 == vE6) {
                    num4.setBackground(Color.green);
                }
                if (v5 == vE1 || v5 == vE2 || v5 == vE3 || v5 == vE4 || v5 == vE5 || v5 == vE6) {
                    num5.setBackground(Color.green);
                }
                if (v6 == vE1 || v6 == vE2 || v6 == vE3 || v6 == vE4 || v6 == vE5 || v6 == vE6) {
                    num6.setBackground(Color.green);
                }

                tV1.setBackground(Color.white);
                tV2.setBackground(Color.white);
                tV3.setBackground(Color.white);
                tV4.setBackground(Color.white);
                tV5.setBackground(Color.white);
                tV6.setBackground(Color.white);

                int res = 0;
                if (vE1 == v1 || vE1 == v2 || vE1 == v3 || vE1 == v4 || vE1 == v5 || vE1 == v6) {
                    res++;
                    tV1.setBackground(Color.green);
                }
                if (vE2 == v1 || vE2 == v2 || vE2 == v3 || vE2 == v4 || vE2 == v5 || vE2 == v6) {
                    res++;
                    tV2.setBackground(Color.green);
                }
                if (vE3 == v1 || vE3 == v2 || vE3 == v3 || vE3 == v4 || vE3 == v5 || vE3 == v6) {
                    res++;
                    tV3.setBackground(Color.green);
                }
                if (vE4 == v1 || vE4 == v2 || vE4 == v3 || vE4 == v4 || vE4 == v5 || vE4 == v6) {
                    res++;
                    tV4.setBackground(Color.green);
                }
                if (vE5 == v1 || vE5 == v2 || vE5 == v3 || vE5 == v4 || vE5 == v5 || vE5 == v6) {
                    res++;
                    tV5.setBackground(Color.green);
                }
                if (vE6 == v1 || vE6 == v2 || vE6 == v3 || vE6 == v4 || vE6 == v5 || vE6 == v6) {
                    res++;
                    tV6.setBackground(Color.green);
                }
                resultado.setText(Integer.toString(res));
            }
        }


    }//GEN-LAST:event_botEmpActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed

    }//GEN-LAST:event_resultadoActionPerformed

    private void tV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tV4ActionPerformed
        do {
            vE4 = Integer.parseInt(tV4.getText());
        } while (vE4 > 0 || vE4 < 50);
    }//GEN-LAST:event_tV4ActionPerformed

    private void tV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tV1ActionPerformed
        do {
            vE1 = Integer.parseInt(tV1.getText());
        } while (vE1 > 0 || vE1 < 50);
    }//GEN-LAST:event_tV1ActionPerformed

    private void tV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tV2ActionPerformed
        do {
            vE2 = Integer.parseInt(tV2.getText());
        } while (vE2 > 0 || vE2 < 50);
    }//GEN-LAST:event_tV2ActionPerformed

    private void tV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tV3ActionPerformed
        do {
            vE3 = Integer.parseInt(tV3.getText());
        } while (vE3 > 0 || vE3 < 50);
    }//GEN-LAST:event_tV3ActionPerformed

    private void tV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tV5ActionPerformed
        do {
            vE5 = Integer.parseInt(tV5.getText());
        } while (vE5 > 0 || vE5 < 50);
    }//GEN-LAST:event_tV5ActionPerformed

    private void tV6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tV6ActionPerformed
        do {
            vE6 = Integer.parseInt(tV6.getText());
        } while (vE6 > 0 || vE6 < 50);
    }//GEN-LAST:event_tV6ActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        if (Borrar == evt.getSource()) {
            contador = 0;
            num1.setText(null);
            num1.setBackground(null);
            num2.setText(null);
            num2.setBackground(null);
            num3.setText(null);
            num3.setBackground(null);
            num4.setText(null);
            num4.setBackground(null);
            num5.setText(null);
            num5.setBackground(null);
            num6.setText(null);
            num6.setBackground(null);
            tV1.setText(null);
            tV1.setBackground(Color.white);
            tV2.setText(null);
            tV2.setBackground(Color.white);
            tV3.setText(null);
            tV3.setBackground(Color.white);
            tV4.setText(null);
            tV4.setBackground(Color.white);
            tV5.setText(null);
            tV5.setBackground(Color.white);
            tV6.setText(null);
            tV6.setBackground(Color.white);
            v1 = 0;
            v2 = 0;
            v3 = 0;
            v4 = 0;
            v5 = 0;
            v6 = 0;
            vE1 = 0;
            vE2 = 0;
            vE3 = 0;
            vE4 = 0;
            vE5 = 0;
            vE6 = 0;
            resultado.setText(null);
        }
    }//GEN-LAST:event_BorrarActionPerformed

    private void bGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGVActionPerformed
        try {
            vE1 = Integer.parseInt(tV1.getText());
            if (contador < 6) {
                check = false;
            }
            if (vE1 == 0 || vE1 > 49) {
                tV1.setText(null);
                vE1 = 0;
                contador--;
            }
            vE2 = Integer.parseInt(tV2.getText());
            if (vE2 == vE1 || vE2 == 0 || vE2 > 49) {
                tV2.setText(null);
                vE2 = 0;
                contador--;
            }
            vE3 = Integer.parseInt(tV3.getText());
            if (vE3 == vE1 || vE3 == vE2 || vE3 == 0 || vE3 > 49) {
                tV3.setText(null);
                vE3 = 0;
                contador--;
            }
            vE4 = Integer.parseInt(tV4.getText());
            if (vE4 == vE1 || vE4 == vE2 || vE4 == vE3 || vE4 == 0 || vE4 > 49) {
                tV4.setText(null);
                vE4 = 0;
                contador--;
            }
            vE5 = Integer.parseInt(tV5.getText());
            if (vE5 == vE1 || vE5 == vE2 || vE5 == vE3 || vE5 == vE4 || vE5 == 0 || vE5 > 49) {
                tV5.setText(null);
                vE5 = 0;
                contador--;
            }
            vE6 = Integer.parseInt(tV6.getText());
            if (vE6 == vE1 || vE6 == vE2 || vE6 == vE3 || vE6 == vE4 || vE6 == vE5 || vE6 == 0 || vE6 > 49) {
                tV6.setText(null);
                vE6 = 0;
                contador--;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "solo se aceptan numeros gilipollas");
        }

    }//GEN-LAST:event_bGVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bonoloto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton bGV;
    private javax.swing.JButton botEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField num3;
    private javax.swing.JTextField num4;
    private javax.swing.JTextField num5;
    private javax.swing.JTextField num6;
    private javax.swing.JTextField resultado;
    private javax.swing.JTextField tV1;
    private javax.swing.JTextField tV2;
    private javax.swing.JTextField tV3;
    private javax.swing.JTextField tV4;
    private javax.swing.JTextField tV5;
    private javax.swing.JTextField tV6;
    // End of variables declaration//GEN-END:variables
}
